apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: gitops
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/bluegreen
    repoURL: https://github.com/kincl/gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
