apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: python-http
  files:
  - app.py
  options:
    disableNameSuffixHash: true
    labels:
      app: python-http

resources:
- service.yaml
- route.yaml
- deployment.yaml
