kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: opencart
spec:
  host: opencart.apps.test-aws-east.sandbox1725.opentlc.com
  to:
    kind: Service
    name: opencart
    weight: 100
  port:
    targetPort: http
