apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: opencart
  includeCRDs: false
  valuesInline:
    opencartHost: opencart
    opencartPassword: user
    mariadb.auth.rootPassword: root
    mariadb.auth.password: opencart
  releaseName: opencart
  version: 12.3.1
  repo: https://charts.bitnami.com/bitnami

namespace: opencart

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: opencart-mariadb
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
