apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projectrequest.yaml

helmChartInflationGenerator:
- chartName: opencart
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 12.3.1
  releaseName: opencart

namespace: opencart

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: opencart-mariadb
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
