apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-namespaces
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cluster-wide/project-namespaces/all
    repoURL: 'https://github.com/kincl/gitops-demo.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
